### ISSUE TITLE
Sample code that writes to an Azure Blob

### ISSUE THREAD

**Issue by dvmorris** [hdinsight/hdinsight-storm-examples#1]
Do you have any sample code where Storm writes out to an Azure blob, rather than HBase? We are having trouble getting any examples to work that do not write to HBase.

**Comment by shanyu** [comment]
Hi Dave,

Yes, the IotSample shows how to write to Azure Blob Storage using the storm-hdfs project.

Thanks,
Shanyu

**Comment by dvmorris** [comment]
Could you send me a URL to that sample code? I cannot find it on GitHub.

**Comment by shanyu** [comment]
The code will be pushed out in a day or so. I appreciate your patience.

Thanks,
Shanyu

**Comment by dvmorris** [comment]
Sounds good. Looking forward to seeing the code!

**Comment by rtandonmsft** [comment]
Please take a look at: IotTopology.java in IotExample

https://github.com/hdinsight/hdinsight-storm-examples/blob/master/IotExample/iot/src/main/java/com/microsoft/hdinsight/storm/examples/IotTopology.java

```java
    //Create HdfsBolt to store data to Windows Azure Blob Storage
    SyncPolicy syncPolicy = new CountSyncPolicy(1000);
    FileRotationPolicy rotationPolicy = new FileSizeRotationPolicy(1.0f, Units.MB);

    RecordFormat recordFormat = new DelimitedRecordFormat().withFieldDelimiter(",");
    FileNameFormat fileNameFormat = new DefaultFileNameFormat().withPath("/iotexampledata/");
    HdfsBolt wasbBolt = new HdfsBolt()
      .withFsUrl("wasb:///")
      .withRecordFormat(recordFormat)
      .withFileNameFormat(fileNameFormat)
      .withRotationPolicy(rotationPolicy)
      .withSyncPolicy(syncPolicy);
    
    topologyBuilder.setBolt("WasbStoreBolt", wasbBolt, 10)
      .fieldsGrouping("DataReferenceBolt", new Fields("model")).setNumTasks(10);
```
