### ISSUE TITLE
Update Newtonsoft.Json

### ISSUE THREAD

**Issue by BennyM** [hdinsight/hdinsight-storm-examples#16]
Please update SCP.Net to use the lastest version of Newtonsoft.Json, or drop the restriction on version number. Adding external packages that depend on a newer version of Newtonsoft.Json is a hassle.

Workaround for now is to force the update of the package.

**Comment by rtandonmsft** [comment]
@BennyM 

A new update for SCP.Net was pushed out today that supports JSON 6,7,8. 
Package: https://www.nuget.org/packages/Microsoft.SCP.Net.SDK/0.9.4.400

Let us know if you see any issues with that.

**Comment by BennyM** [comment]
Hi

Thanks! Are there release notes available?
