### ISSUE TITLE
Where logs are writing?

### ISSUE THREAD

**Issue by dsevastianov** [hdinsight/hdinsight-storm-examples#7]
Hi, more of a question, is there a way to see what Context.Logger outputs in topology running on Storm?

**Comment by rtandonmsft** [comment]
For SCP.Net I had posted about logs in this MSDN forum post:
https://social.msdn.microsoft.com/Forums/azure/en-US/8a1b48a3-2617-4a2c-980f-4022005a9afa/question-about-logging-in-storm-with-hdinsight?forum=hdinsight

## Few excerpts from the post:
* SCP.Net runs your C# Spout or Bolt as an executable under the same worker JVM. It uses Log4Net as its logging framework, by default the logs for SCP.Net go to %STORM_HOME%\logs\scp or wherever you have configured the Log4Net section in Microsoft.scp.dll.config or your app.config file. Essentially you can control this.

* NOTE: The spout and bolt tasks run on worker nodes, so their logs are available on respective worker nodes where they are running, you can find this information in Storm UI. When you enable RDP on HDInsight cluster, it enabled it on all nodes, so you can also rdp into workernode0, workernode1, headnode1, zookeeper0 etc from within your rdp session via mstsc. You can then browse or execute commands on that node too. In this case, check out physical log files or task manager on worker nodes to see the logs or cpu/memory consumption.

* If you wish to see logs from your entire cluster in one place without going into each node, you can use the hadoopservicelog table in your storage account (the one used during cluster deployment).
Table Name format: u + <clustername> + "at" + <datetime> + "hadoopservicelog"
Refer to this blog post for details:
http://blogs.msdn.com/b/brian_swan/archive/2014/01/06/accessing-hadoop-logs-in-hdinsight.aspx

## Future:
We also investigating other ways to expose these logs in a better and more accessible way.
Feedback and suggestions are welcome!

**Comment by dsevastianov** [comment]
Thank you

**Comment by rtandonmsft** [comment]
dsevastianov - Next NuGet update of SCP.Net will help you get the logs of SCP.Net in your Java Worker logs.

<b>How to get them now?</b>
SCP.NET logs logged using Context.Logger can be displayed in Storm worker log files now, you will be also able to see them from VS/Storm UI.

There are two log pipelines from SCP.NET process to Storm worker, one is for STDERR, the other is for STDOUT.

You can control the log level of each pipeline by changing the threshold of ConsoleAppenderError and ConsoleAppender, which can defined in ```Microsoft.SCP.Net.SDK\sdk\Microsoft.SCPNet.dll.config```.

Add these appenders to the log4net section:

```xml
<log4net>
    <appender name="ConsoleAppenderError" type="log4net.Appender.ConsoleAppender">
      <threshold value="ERROR"/>
      <target value="Console.Error" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="[%thread] %-5level %logger - %message%newline" />
      </layout>
    </appender>
    <appender name="ConsoleAppender" type="log4net.Appender.ConsoleAppender">
      <threshold value="INFO"/>
      <target value="Console.Out" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="[%thread] %-5level %logger - %message%newline" />
      </layout>
    </appender>
```

Add these appenders in your root logger configuration to start seeing the logs.
```xml
    <root>
      <level value="INFO" />
      <appender-ref ref="ConsoleAppenderError" />
      <appender-ref ref="ConsoleAppender" />
```

You can checkout the same in this template: https://github.com/hdinsight/hdinsight-storm-examples/blob/master/templates/AzureEventHubsReaderStormApplication/Microsoft.SCPNet.dll.config

**Comment by dsevastianov** [comment]
Thank you Ravi
